services:
  assemulator:
    image: __IMAGE__
    container_name: __APP__
    restart: unless-stopped
    environment:
      NEXTCLOUD_BASE_URL: __NEXTCLOUD_BASE_URL__
      NEXTCLOUD_SHARE_TOKEN: __NEXTCLOUD_SHARE_TOKEN__
      NEXTCLOUD_METADATA_PATH: __NEXTCLOUD_METADATA_PATH__
    ports:
      - "127.0.0.1:__PORT__:80"
    volumes:
      - __APPDIR__/roms:/usr/share/nginx/html/roms
      - __APPDIR__/images:/usr/share/nginx/html/images
      - __APPDIR__/bios:/usr/share/nginx/html/bios
